config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  resources :product

  resources :user

  get 'login' => 'logins#new'
  post 'login' => 'logins#create'
  delete 'logout' => 'logins#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize_user
      redirect_to :back, :status => 401 unless current_user.account_type == "admin_user"
      #redirects to previous page
  end


  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id])
  end

  helper_method :current_user
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to product_index_path
    end
  end

  def destroy
    @current_user = session[:current_user_id] = nil
    flash[:notice] = "You have successfully logged out."
    redirect_to '/'
  end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  before_filter :authorize_user, :except => [:index, :show]

  def index
    @products = Product.all
  end

  def new 
    @product = Product.new
  end

  def create
  end
  
  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def destroy
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :in_stock, :photo_url, :skew)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  

  def new 
    @user = User.new
  end

  def create 
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path
    else
      flash.now[:error] = "Could not save"
      render action: "new"
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password_digest)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MasterCupcakes</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300,500' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/logins/new.html.erb
<h2>Login</h2>

<%= form_tag login_path do %>
  <div>
    <%= label_tag "email" %><br />
    <%= text_field_tag :email %>
  </div>
  <div>
    <%= label_tag "password" %><br />
    <%= password_field_tag :password %>
  </div>
  <div>
    <%= submit_tag "Log In" %>
  </div>
<% end %>

app/views/product/_form.html.erb
<main>
<br>
<%= form_for @product, :html => {:multipart => true} do |f| %>
  <% if @product.errors.any? %>
    <div>
      <%= pluralize(@product.errors.count, "error") %> prevented this product from being submitted.
        <ul>
          <%= @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "Name" %>
    <%= f.text_field "name" %>
  </div>
  <div>
    <%= f.label "Description" %>
    <%= f.text_field "description" %>
  </div>
  <div>
    <%= f.label "Price" %>
    <%= f.text_field "price" %>
  </div>
  <div>
    <%= f.label "Number of units in stock" %>
    <%= f.text_field "in_stock" %>
  </div>
  <div>
    <%= f.label "Skew" %>
    <%= f.text_field "skew" %>
  </div>
  <div>
    <%= f.label "Photo Url" %>
    <%= f.text_field "photo_url" %>
  </div>
  <div>
    <%= f.submit "Submit"  %>
  </div>
<% end %>

</main>

app/views/product/edit.html.erb
<%= render 'form' %>

app/views/product/index.html.erb
<section>
  <img src="/images/product-header.jpg" class="header-image" />
</section>
<%= react_component 'Products', data: @products %>

app/views/product/show.html.erb
<%= react_component 'OneProduct', data: @product %>

app/views/shared/_nav.html.erb
<div class="container-fluid navigation-outer">
  
  <% if current_user %>
    Hi <%= current_user.first_name %>

    <%= link_to "Add Product", new_product_path %>



    <%= link_to "Log Out", logout_path, method: :delete %>
  <% else %>
    Please <%= link_to "Login", login_path %>
    
  <% end %>

  
</div>